CREATE TABLE IF NOT EXISTS Environments(

    dbID VARCHAR(255),
    SnapNum INT(16),
    SubfindID INT(32),
    MaxMassType_stars FLOAT,
    
    Mini_R1 FLOAT,
    Mini_R2 FLOAT,
    Mini_R3 FLOAT,
    Mini_R4 FLOAT,
    Mini_R5 FLOAT,
    Mini_M1_stars FLOAT, 
    Mini_M2_stars FLOAT, 
    Mini_M3_stars FLOAT,
    Mini_M4_stars FLOAT,
    Mini_M5_stars FLOAT,
    Mini_Nin50kpc INT(16),
    Mini_Nin100kpc INT(16), 
    Mini_Nin500kpc INT(16),
    Mini_Nin1Mpc INT(16), 
    Mini_Nin2Mpc INT(16),
    Mini_MassIn50kpc_stars FLOAT,
    Mini_MassIn100kpc_stars FLOAT,
    Mini_MassIn500kpc_stars FLOAT,
    Mini_MassIn1Mpc_stars FLOAT,
    Mini_MassIn2Mpc_stars FLOAT,
    
    Minor_R1 FLOAT,
    Minor_R2 FLOAT,
    Minor_R3 FLOAT,
    Minor_R4 FLOAT,
    Minor_R5 FLOAT,
    Minor_M1_stars FLOAT, 
    Minor_M2_stars FLOAT, 
    Minor_M3_stars FLOAT,
    Minor_M4_stars FLOAT,
    Minor_M5_stars FLOAT,
    Minor_Nin50kpc INT(16),
    Minor_Nin100kpc INT(16), 
    Minor_Nin500kpc INT(16),
    Minor_Nin1Mpc INT(16), 
    Minor_Nin2Mpc INT(16),
    Minor_MassIn50kpc_stars FLOAT,
    Minor_MassIn100kpc_stars FLOAT,
    Minor_MassIn500kpc_stars FLOAT,
    Minor_MassIn1Mpc_stars FLOAT,
    Minor_MassIn2Mpc_stars FLOAT,
    
    Major_R1 FLOAT,
    Major_R2 FLOAT,
    Major_R3 FLOAT,
    Major_R4 FLOAT,
    Major_R5 FLOAT,
    Major_M1_stars FLOAT, 
    Major_M2_stars FLOAT, 
    Major_M3_stars FLOAT,
    Major_M4_stars FLOAT,
    Major_M5_stars FLOAT,
    Major_Nin50kpc INT(16),
    Major_Nin100kpc INT(16), 
    Major_Nin500kpc INT(16),
    Major_Nin1Mpc INT(16), 
    Major_Nin2Mpc INT(16),
    Major_MassIn50kpc_stars FLOAT,
    Major_MassIn100kpc_stars FLOAT,
    Major_MassIn500kpc_stars FLOAT,
    Major_MassIn1Mpc_stars FLOAT,
    Major_MassIn2Mpc_stars FLOAT,
    
    PRIMARY KEY (dbID)
);

