CREATE TABLE IF NOT EXISTS MorphSersic_HSC_X(

	dbID VARCHAR(255),
	SnapNum INT(16),
	SubfindID INT(32),
	axis VARCHAR(255),
	
	redshift FLOAT,
	apmag FLOAT,
	dr VARCHAR(255),
	rerun VARCHAR(255),
	ra FLOAT,
	decl FLOAT,
	
	Sersic_Ieff FLOAT,
	Sersic_dIeff_m FLOAT,
	Sersic_dIeff_p FLOAT,
	Sersic_Reff FLOAT,
	Sersic_dReff_m FLOAT,
	Sersic_dReff_p FLOAT,
	Sersic_n FLOAT,
	Sersic_dn_m FLOAT,
	Sersic_dn_p FLOAT,
	Sersic_phi FLOAT,
	Sersic_dphi_m FLOAT,
	Sersic_dphi_p FLOAT,
	Sersic_q FLOAT,
	Sersic_dq_m FLOAT,
	Sersic_dq_p FLOAT,
	Sersic_X FLOAT,
	Sersic_dX_m FLOAT,
	Sersic_dX_p FLOAT,
	Sersic_Y FLOAT,
	Sersic_dY_m FLOAT,
	Sersic_dY_p FLOAT,
	Sersic_e1 FLOAT,
	Sersic_de1_m FLOAT,
	Sersic_de1_p FLOAT,
	Sersic_e2 FLOAT,
	Sersic_de2_m FLOAT,
	Sersic_de2_p FLOAT,
	Sersic_Itot FLOAT,
	Sersic_dItot_m FLOAT,
	Sersic_dItot_p FLOAT,
	Sersic_mag FLOAT,
	Sersic_dmag_m FLOAT,
	Sersic_dmag_p FLOAT,
	Sersic_chi2nu FLOAT,
	
    Petro_R FLOAT,
    Petro_Rc FLOAT,
	CAS_C FLOAT,
	CAS_A FLOAT,
	CAS_S_abs FLOAT,
	CAS_S_pos FLOAT,
	R_A FLOAT,
	Gini FLOAT,
	M20 FLOAT,
	Shape_A FLOAT,
	RFF FLOAT,
	Sigma1kpc FLOAT,
	
	skyMean FLOAT,
	skyMedian FLOAT,
	skySigma FLOAT,
	nPixGalaxy INT(32),
	nPixSky INT(32),
	nPixTotal INT(32),
	sepFlag INT(8),
	runTime FLOAT,
	seed INT(32),
	PRIMARY KEY (dbID)
);
