CREATE TABLE IF NOT EXISTS Subhalos(

    dbID VARCHAR(255),
    SnapNum INT(16),
    SubfindID INT(32),
    
    SubhaloMassType_stars FLOAT,
    SubhaloMassType_gas FLOAT,
    SubhaloMassType_dm FLOAT,
    SubhaloMassInRadType_stars FLOAT,
    SubhaloMassInRadType_gas FLOAT,
    SubhaloMassInRadType_dm FLOAT,
    SubhaloHalfMassRadType_stars FLOAT,
    SubhaloHalfmassRadType_gas FLOAT,
    SubhaloHalfmassRadType_dm FLOAT,
    SubhaloBHMass FLOAT,
    SubhaloBHMdot FLOAT,
    SubhaloMass FLOAT,
    SubhaloSFR FLOAT,
    SubhaloSFRinHalfRad FLOAT,
    SubhaloSFRinRad FLOAT,
    SubhaloVelDisp FLOAT,
    SubhaloVmax FLOAT,
    SubhaloVmaxRad FLOAT,
    
    SubhaloGrNr INT(32),
    GroupFirstSub INT(16),
    GroupNsubs INT(32),
    GroupMass FLOAT,
    GroupMassType_stars FLOAT,
    GroupMassType_gas FLOAT,
    GroupMassType_dm FLOAT,
    Group_M_Crit200 FLOAT,
    Group_M_Crit500 FLOAT,
    Group_R_Crit200 FLOAT,
    Group_R_Crit500 FLOAT,
    GroupVelDisp FLOAT,
    GroupVelDisp_Z FLOAT,
    GroupVelDispMassWeighted FLOAT,
    GroupVelDispMassWeighted_Z FLOAT,
    SubhaloPosInGroup_X FLOAT,
    SubhaloPosInGroup_Y FLOAT,
    SubhaloPosInGroup_Z FLOAT,
    SubhaloVelInGroup_X FLOAT,
    SubhaloVelInGroup_Y FLOAT,
    SubhaloVelInGroup_Z FLOAT,
    GroupCM_X FLOAT,
    GroupCM_Y FLOAT,
    GroupCM_Z FLOAT,
    GroupPos_X FLOAT,
    GroupPos_Y FLOAT,
    GroupPos_Z FLOAT,
    GroupVel_X FLOAT,
    GroupVel_Y FLOAT,
    GroupVel_Z FLOAT,

    PRIMARY KEY (dbID)
);
